/**
* This file is auto-generated by nestjs-proto-gen-ts
*/

import { Observable } from 'rxjs';
import { Metadata } from '@grpc/grpc-js';

export namespace category {
    // tslint:disable-next-line:no-empty-interface
    export interface CategoryService {
    }
    export interface CreateCategoryInput {
        name?: string;
    }
}

