/**
* This file is auto-generated by nestjs-proto-gen-ts
*/

import { Observable } from 'rxjs';
import { Metadata } from '@grpc/grpc-js';

export namespace common {
    export interface AffectedRows {
        AffectedRows?: number;
    }
    // tslint:disable-next-line:no-empty-interface
    export interface Empty {
    }
}

