/**
 * This file is auto-generated by nestjs-proto-gen-ts
 */

import { Observable } from 'rxjs';
import { Metadata } from '@grpc/grpc-js';

export interface TweetService {
  createTweet(
    data: CreateTweetInput,
    metadata?: Metadata,
  ): Observable<common.AffectedRows>;
}
export interface CreateTweetInput {
  Content?: string;
  AccountID?: number;
  Categories?: CreateCategoryInput[];
}

// tslint:disable-next-line:no-empty-interface
export interface CategoryService {}
export class CreateCategoryInput {
  name?: string;
}

export namespace common {
  export interface AffectedRows {
    AffectedRows?: number;
  }
  // tslint:disable-next-line:no-empty-interface
  export interface Empty {}
}
